FirefoxCSS-Store/FirefoxCSS-Store.github.io

- index.html
Imma do it myself then /s
Just saw the post, contributing with my theme and good luck with the website.
> Added Firefox-UWP-Style

- README.md
- index.html
Not too much, but enough to help.
> Fixed typos and better reading of readme.

- assets/css/main.css
- assets/sass/components/_poptrox-popup.scss
> fixed responsible css

- themes.json
Hey!! I just added my theme to this beautiful collection
> Sweet_Pop! theme added

- themes.json
Hi! @Neikon I didn't know how the order is but I added my theme as the last one in the list. This one is an awesome project and I'll share it to reach more people! Thank you!
> Added Simplerentfox

- themes.json
> Add last updated date to themes

- themes.json
Firefox theme repository renamed to `Sweet-Pop`
> Repository name update

- themes.json
I added a new theme called Natura, inspired by nature vibes. Hope y'all like it : )
> Added new theme Natura

- themes.json
> Added PretoFox.

- themes.json
I've added my new theme in this commit.
> Added my new theme GentleFox

- README.md
There were some obvious grammar mistakes in README. 
Also, the code example was using tabs instead of spaces which is also used by the 'themes.json'. So, the tabs are replaced for consistency.
>  Fixed syntax and punctuation 

- dev/js/main.js
- dev/pug/includes/header.pug
Fixes #30.
---
My bad, took only 9 months to get it working.
---
Seriously though, I lost my computer and I was lazy when I got a new one, sorry for taking too long.
> dev: add sorting switcher

- themes.json
> Added AuroraFox

- themes.json
Hi I'd like to submit a pull request to get my theme published in the FirefoxCSS-Store, thanks
> Firefox-UWP-Style-Theme-Omars-Edit

- README.md
There are multiple versions of Windows, even Windows 11. This PR will remove the number in "Windows 10" to ensure nobody asks "Is my system compatible with this?".
> Remove the "10" in "Windows 10"

- dev/scss/base/_scaffholding.scss
- dev/scss/components/_buttons.scss
- dev/scss/components/_card.scss
- dev/scss/utilities/_variables.scss
A darker dark-mode, with colors from a color palette ([tailwindcss](https://tailwindcss.com/docs/customizing-colors) slate-700, slate-800). And some different white shades (Anti-Flash White, Chinese White).
Additionally a lighter glow instead of a normal shadow when dark-mode is applied to prevent a dark shadown on dark backgound.
These are of course stylistic changes so feel free to reject the PR if it doesn't fit the style :)
> Darker dark-mode

- themes.json
> add Firefox Plus

- themes.json
> themes.json: add minimal arc

- themes.json
This PR introduces a custom Firefox theme that I created, focused on minimalism and aesthetics. The theme aims to provide users with a clean, distraction-free browsing experience that complements Firefox’s user interface while offering a visually appealing look.
> MiniSthetic_Firefox: Minimalist & Aesthetic Theme for Firefox

- themes.json
> 300-newtheme-elegant-floorp
